apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: iioflux
  namespace: iioflux
spec:
  interval: 5m
  chart:
    spec:
      chart: iioflux
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: jonkerj
        namespace: flux-system
  values:
    image:
      tag: v3
    config:
      hosts:
      - name: neon
        uri: ip:172.21.42.10
        devices:
        - name: bme280
          match:
            name: bme280
      influxdb:
        connection:
          host: influxdb.influxdb
          port: 8086
          database: iioflux
    existingSecret: iioflux-secret
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
