apiVersion: v1
kind: Secret
metadata:
    name: iioflux-secret
    namespace: iioflux
data:
    influxdb.connection.username: ENC[AES256_GCM,data:zAcKSv11Tqls8yfL,iv:NYKtV1vxA/gImhE4oEWBXwVRaFQ4a4Fq4zFOpilCd80=,tag:LfPK4Kp240elypejfAsMNA==,type:str]
    influxdb.connection.password: ENC[AES256_GCM,data:xt8RpfNW1HEesXKVV+k1mQ==,iv:7g0pp2bIcOAGzva49BrqVP4WnaRb5nm3hMP7yRgP5qw=,tag:3VwGyI8jz8iF2+JYkFq75A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-07T17:44:09Z'
    mac: ENC[AES256_GCM,data:dw2PevWIe3PbmSST2aLsysBhnYMDIgCv0JB2WelNTCYFZuXQTYoWHqPSyulstkN3k4e7USeSJkMONZdgV6+A0RfHIuJ+UtjsDOl5ZfZ2glHEJrXT49zm89Okx8mwmGbQlwwDUrUF7mIshBwDi/s3U2UD9tFhXe1ymazEmpOi2Qw=,iv:T9Js5MnCDXYNG66rTCtwQEDP0FcAHuMKTW5j05I9fTc=,tag:+ooqj8CAWLMefXgKfyWB+w==,type:str]
    pgp:
    -   created_at: '2021-03-23T16:09:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ//eMyDDurNm62noNxeuMFrUlmyzuV1ImRD4bYtOW2AP8Ih
            qTHbMR+HAp3uY8kUMlrXlNsHrSGb+NUol+7A5i88YWvIxT+fLzEiaqfUZDUaL0vi
            HfcBMlaso+bmro0YjIFyXQ4An2EkMF3YsYmdqiqkgh7o65euCYSYMs1X6DeXEZW4
            M+WjLC8oNN8JA1C9N9wSEjDUi1zT5bY+w1FaA/14jUf82kq/ziWt+ZxalcqYm4lU
            4qVtXIIhY0Ve01q3kStp1hn3V84xajVFkfgufi19La4dqsvL+lnGeQRMBzXJOj2n
            ctTLQA/OE3/YyNgO5uN74/awUoU0C4yKHzxs10XcbxjPIFhhY1hcBMbSmxaJkb5+
            BhUBVPKSBeKBhDBEjZ6KuZfl/7ZXVSwwmUPa7olGBch4TI4yV4ysqwxDY7A8js+U
            TDB0GyH8YlOlBXg8iYPeeF/ggYF6gapEm5/gOCTrhrhob2bktVClfGmFn83+PhbU
            lUsAgMNP+Y1zB4WCZDlQH7L4fkF83DK4a0y6cVSyPWNvsKP44pyVlHmv2L7vuaqW
            zPmTNaR4IlAUJ5R0rKIknXHUT/NJ4KpYeIqHukfpynb5qOxY6cFHFviBTQSeqsNU
            6vMWYeANF2xvXuX7X/M4UaW7cc+wybiU+IiA8WKqRNuiXA/PI96JM+Du2dUX33vS
            XgEb+uiD9/ErO9rmOe66ckWWxUHQ+/4sNs1yePCte6o7TDYfIqTm4c0cfwMKDK1b
            ELNVul/LA3dRBv8Sg77qtx5it7W9yVdT7yXvs4jo0Xa5Hk5r9TLsBy8yuKTfiyw=
            =NYxl
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
