apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: v1.2.0
  interval: 10m
  install:
    skipCRDs: true
  values:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 250m
        memory: 250Mi
    cainjector:
      resources:
        requests:
          cpu: 50m
          memory: 75Mi
        limits:
          cpu: 250m
          memory: 250Mi
    webhook:
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 250m
          memory: 100Mi
