apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-hubble
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret-cilium
    extraArgs:
      provider: "oidc"
      oidc-issuer-url: "https://sso.9ka.nl/auth/realms/9ka"
      email-domain: "kippendief.biz"
      skip-provider-button: "true"
      upstream: "http://hubble-ui/"
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts: ['hubble.t.efgh.nl']
      tls:
      - hosts: ['hubble.t.efgh.nl']
        secretName: hubble-tls
