apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  config:
    publicUrl: http://neon.thuis.efgh.nl:9000
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://neon.thuis.efgh.nl:9000
  objectStorage:
    bucket: velero
  provider: aws
