apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: backup
  namespace: velero
spec:
  schedule: '@every 24h'
  template:
    storageLocation: default
    includeClusterResources: true
    ttl: 732h
