apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smapy
  namespace: smapy
spec:
  interval: 5m
  chart:
    spec:
      chart: smapy
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: jonkerj
        namespace: flux-system
  values:
    env:
      INFLUXDB_V2_BUCKET: 'solar/autogen'
      INFLUXDB_V2_TAG_LOCATION: 'gareelhoek'
    envSecret: smapy-secret
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
