apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: smapy
  namespace: smapy
spec:
  interval: 5m
  chart:
    spec:
      chart: smapy
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: jonkerj
        namespace: flux-system
  values:
    image:
      tag: v0.2.1
    config:
      influxdb:
        host: influxdb.influxdb
        port: 8086
      interval: 30
      tags:
        location: gareelhoek
    existingSecret: smapy-secret
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
