apiVersion: v1
kind: Secret
metadata:
    name: smapy-secret
    namespace: smapy
data:
    influxdb.password: ENC[AES256_GCM,data:oIS9Mgpq+hxOuJ7gyhlWpg==,iv:QalR+TyzA+nmP9ANTNzq8Psf9dFXMrUCNaIwfDKXucQ=,tag:8kk0lWnq5pMPf65Q0BXRgQ==,type:str]
    influxdb.username: ENC[AES256_GCM,data:qY9XXCV4r+4=,iv:t68T2XL4+XQ12YIrtT7QlXFH6fgXOpqaDflEsPO6pzo=,tag:3vFpyqLQ/26dx+WcrteGtw==,type:str]
    influxdb.database: ENC[AES256_GCM,data:aYGaFFyBOEU=,iv:YXtSPNWmNQT1WHa7QE0f4XsvhSbkUaFiEfuIow6QiU8=,tag:ALoa3zMNvumgk7SdPuxR2A==,type:str]
    sma.group: ENC[AES256_GCM,data:pgjsrQ==,iv:+OfbFg6L86lCe0TYbKG0d5Z51VOXw0jlcDQydHqKQZA=,tag:b8slY0eBLDX/eB6Q2IYrDA==,type:str]
    sma.password: ENC[AES256_GCM,data:f0YPKORENAJw4KUe55aWbQ==,iv:EzTzIK6QK9mL5sdMVNTughZcHUXleyUi6QywIeguKWg=,tag:mHGgmYPga2jZLsywHMzyOw==,type:str]
    sma.url: ENC[AES256_GCM,data:mujuHywLP/n6TF9Lz9YSdOrscOgKbxaCk12c4bEhark=,iv:FI1ESHAgTp+s/lU/lNwjn8WmLef3towLzfG3Es8iSRs=,tag:+mNetzWrA0M+NifrRbkn0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-07T17:44:56Z'
    mac: ENC[AES256_GCM,data:AYigq+7rjsPJpacPzZK/uOH0a8GNl7RqfDfn3qxN7SE0ipzuCnTt3GXALBIAO08eu6KSKErnvjP2DIbMOgA7RsPZhp4yEODwHBgeyfzzCrVx/tR7jvWealIl/ZwnK/hZhUI/KJpIg3JvQCVGZPTA40ZJN6jBwRu8f+GLun0f+U8=,iv:jLJ24kJvSTYj05Ffnd2egtTKaqPnnwjcF4W0rL1Nqtg=,tag:VwL1v9FXCkJiG9W6nzYpIg==,type:str]
    pgp:
    -   created_at: '2021-03-29T14:04:55Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ/9Fo6jvr2dGcGTWbM0FGytTxHBS7D6XU7cqqpl0p6QdtXd
            SXCpN4CuclwcnCugDPOeJGCYiKyMF3meHI8XgXSN+aV/aJZqJBqhvievKaUvAuTL
            C7qt1XwWejclHs1CdUQwZOkRgcxF0tzTdYE0fGO+ZktcNfnWKEsq8PQBrUEXLaMi
            dUJeyvX7sy1ulxpJh2ND03zcrI3+qKdiOguTGVqTKef61Sv8f0ExP+cRanAThWMJ
            i+Cz7UojCOZtw7MHo/ab8vieReovfo0mwExy02K0zZC45d/4uFv0w2NuN5C5uQdj
            znq4ZMbFeaX7/r9HXOQsVlLoZ2jt749Ei3ZIBWKd7lr/XnCmFdmCE4NNmue535go
            10ZzmFw+ERNcQHMwQm5kUPKqHDiQQ8v+q0vxk13QCSEJiGOeMuZuksVC4uZhzRfS
            UzaNLlO/RfRgXGN2aWkQQJhnSyj8IxJEK1u/yczfpozQnxeA5GBxw/3Bjoh5ssXY
            dmWr89rvfeTrsIeVw+WGbfRB/3iv3D9zWeookYnU7/m5FaKJuC9MDRHFdOT2XHDK
            3MzXHsKn5aqwaBEa/G8QUqtHv+GTRUqi/8UmxowKQ39WYYYkKVSoP5GIaESOtQxR
            yiIh6F3PiaMQnHCd3FP+agS0hWln+ucCK8Z357qZehFiVPHUPxy5tlfosQOSf8rS
            XAHE784zF25O3NK+/W2N3Bc2CCalCCjin7nJnsZ1ZmOwqIlnkkkF0+/8ZJmw+wfs
            CA3qDj8hS6hp2syVTUKhzWbEFd92iCLSiQJEk8k+WytfPegpzNuGWMGjU6qW
            =Tr05
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
