apiVersion: v1
data:
    token: ENC[AES256_GCM,data:7pilCnjXg8wcPBR9AogLQdoqB5c2MdEhH5rQOH1JQ+w=,iv:mJEWcA25EHaGrzT7LvEd/BQpUmtuTtjG/M8qiNIss8Q=,tag:bTzfdOi2cQqXG5YiT3vQ0g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: talos-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-12T10:35:26Z'
    mac: ENC[AES256_GCM,data:4hqijVVZHZxics3LwkVN+r6d+6svU2tcbJNGoBcmwd/yJm/VvKwWfq4L1lWkaVpUMHunbEepGeCymUa3KAooDQ5V/Wi/tTyQnQl+ABs1Iiy1vr0QGAeL2xa3ra8A53MpdGtHUSSCVuPJ9tfNe+HiefU8JQz03zchyPFB1p/VigM=,iv:/+kCCsl7Sq+OJGRCAd3imwZDTi7DcH6IBURPj5BIRig=,tag:VhXQwWebaJa05gN3J5iaHA==,type:str]
    pgp:
    -   created_at: '2021-02-12T10:35:25Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAArinMbVUyKlufxcZlBLKuJqcEW7DU4FgWk4Q1mOmOQv14
            F5Po/ewOOv/Iq62kFyxwnXtkRQXDzj2CPdHe2WMYif79D78+aOcOEm22N+E9ilOB
            rHqyr3WYFuqCuT+/LU+LUMDZUQyNvr9iMWEfKey9RERASP8Lit0Y0tkPRdK5ZotE
            h0/Dp54HFsKnBmpY9prPczGYnV4EHduB5oeYlXP8TeKAeKGW+nSvD/PV4YIxlbhQ
            GspazV7nyfBmlRzStHpt6DJkstNHBhtOKeerzAKzjCqAd+IUycRIZ+LOebBEj6ym
            XvhNU/w2arnMC4rdstPQBygX70yZUT2/YNs1UqLIHkl9HDXwB6JT5JM9WH/sudkE
            2ejduGIw78gsS5ui3atV01nBVQblY+jgusxSEKR3bfaHYkgCbOYcPzgWCm1zaxTR
            kYiVP6D6I3xE0bXA9PyoOJbhHMeQYm1Y3eNVMHypum/pHwxOg382hO4For6TFzgL
            vmFwZZw4JZ6XfGjOs64EXufMBFrWXNM3AjErodTGYrplP/uvUhVEIncGjfq4hDWx
            aVVbUYqawKWv2ac6tj9p8bhwPnItnUfBMh66acLMNjK4nzSsAC0ZrMHqs2cZMKTe
            EDtWNmprH6YhAw1rk7i8xueTnWLcweYBr+u5J/C9FYiSE8AjcRJ3WfxdKgQI/0jS
            XgHr18WgczzvPPcyUDWZMID2gMtoJPGBAYMP8AzMQdz3Zn86mLHrOIWmyImyQ9mS
            8J0Ivs3jtCJ11KXeNUnIesoaqxuhPH9OadH8G5po169zj1WYAZtb9NXdtldex90=
            =2N8q
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
