apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 13.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    fullnameOverride: kps
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    coreDns:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: true
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: true
      serviceMonitor:
        relabelings:
        - sourceLabels:
          - "__meta_kubernetes_pod_node_name"
          targetLabel: node_name
    nodeExporter:
      serviceMonitor:
        relabelings:
        - sourceLabels:
          - "__meta_kubernetes_pod_node_name"
          targetLabel: node_name
    grafana:
      persistence:
        enabled: true
        size: 1Gi
      admin:
        existingSecret: grafana-admin-user
      envFromSecret: grafana-env-vars
      extraSecretMounts:
      - name: auth-generic-oauth-secret-mount
        secretName: grafana-generic-oauth
        defaultMode: 0440
        mountPath: /etc/secrets/auth_generic_oauth
        readOnly: true
      grafana.ini:
        server:
          root_url: https://grafana.t.efgh.nl
        paths:
          data: /var/lib/grafana/data
          logs: /var/log/grafana
          plugins: /var/lib/grafana/plugins
          provisioning: /etc/grafana/provisioning
        analytics:
          check_for_updates: false
        log:
          mode: console
        grafana_net:
          url: https://grafana.net
        auth.generic_oauth:
          enabled: true
          name: 9ka
          allow_sign_up: true
          client_id: $__file{/etc/secrets/auth_generic_oauth/client_id}
          client_secret: $__file{/etc/secrets/auth_generic_oauth/client_secret}
          scopes: openid profile email
          auth_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/auth
          token_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/token
          api_url: https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/userinfo
          allowed_domains: kippendief.biz
        users:
          allow_org_create: false
          auto_assign_org: true
          auto_assign_org_role: Admin
        security:
          allow_embedding: true
      ingress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        enabled: true
        hosts:
        - grafana.t.efgh.nl
        tls:
        - secretName: grafana-tls
          hosts:
          - grafana.t.efgh.nl
      plugins:
      - fetzerch-sunandmoon-datasource
      sidecar:
        datasources:
          searchNamespace: ALL
        dashboards:
          searchNamespace: ALL
      resources:
        requests: 
          cpu: 150m
          memory: 100Mi
        limits:
          cpu: 1
          memory: 200Mi
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    prometheus:
      enabled: false
    prometheus-node-exporter:
      extraArgs:
      - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
      - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
      - --collector.mountstats
