apiVersion: v1
data:
    INFLUX_PASSWORD: ENC[AES256_GCM,data:QsPMEBzxQRh5kpQdhbKnug==,iv:aSn2mh2LZcww+3bS1022ymoH+V8LtzP/1ck8Gea+TMU=,tag:BMZvDxJzF5PNf9TSXvS5AQ==,type:str]
    INFLUX_USER: ENC[AES256_GCM,data:wtLeJtFkZtI=,iv:CAbN6FZfkQjGrF2b4fIJ7xTcBSHuYH1rWvppHrJoKqM=,tag:cgJNMG+pdbITdyrmSjcYmA==,type:str]
kind: Secret
metadata:
    name: grafana-env-vars
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-22T13:52:48Z'
    mac: ENC[AES256_GCM,data:5t7IruD0iMjP7NPaksMPWPjkSyVavuvMxOdh8VMx4kcJk36QRjynSWBRuO4A5LUlrfTRuyWSzCBqxlY9vTSiw3IxILEpQNDljjmU4SIUK/ec7/uEFPH/yiXfs7akxHPTMGQAddl+oeNjOR5Zn/LsJwNyUTY79iBtP6kNCU0Urwg=,iv:OXoQ+Efau0kbGYCNvqCbKl+nUCBhmOhe7IYDUvlf5/c=,tag:/2dDJxaCsqnz0DSvWlcc+w==,type:str]
    pgp:
    -   created_at: '2021-02-22T13:52:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ//SNf6Xundes4aiD9OOVfbRvTQkqmOATIjWnTY2Dhchgs8
            2OlDviNPO0vlVM1BLkJokpdRDAXMSQvVK1enWJKhbJxcGj4FEMaNZtFXvrjDTSGW
            nfgvpbNGrX7hL2heoDycZz/CoNLSoyxLpk6EciHHufliMZdy3+IgoVL4zc+3Ckpz
            NzU7W3cATtjwZTF8ydu2YaZZuI/hzKdh0rzArQoGQk7UokRfUqpS0whHcEEevn7G
            x66had+ojLqpgDueUZER2QZJOuz9YEIudvTsx8jn9pNlvfwt/Gl9VvsrOsj9sW8V
            TZBTTtjwzKZrqADR+bAu+PGc+flCj3NV4sG2jZji/idHr+pQKQrgRWjOwzpiyMzD
            TEo7U0pSawSU1foVjhpTAyiWhH7QNi4lWpFBgVdYQc9j+duCdM6+x1Cgpn5BwjY2
            Gpw5bHIxkET1QC1IG0a6+cva+wo3LABhrA5z9yb2NAeiznJ/ox7ZISLWRE5SSIZf
            WhqK7Ujsv+20FjGRXNgvqPT/htvQZuAdl3NL4tZgSj83/N0tK263Jo5uJ83AEjoT
            54D2zzsn5GDwDSi9Y74ohz/EBkyjjKcezWTSKwsqLEJs9X081IyQMp4onvxgpJ+I
            +NmB3/AVN4NQCuOyYvCmlGA6DSpe2wmXj55hokT5vnp+92vo0xjmv10EoSixYgfS
            XAGh64URnVzYsNBOmx1LQgqroWLs1o9Vw85li7zIWFapq8EGKsrZXcyTTzOYRDkt
            N7sI40simzu26dyzr9PBiCrlN+9QTjjd8m9+x4XGV0VHxXNBVyTMXFzOrFPr
            =v8Mg
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
