apiVersion: v1
data:
    password: ENC[AES256_GCM,data:SDn9PePRnkQSIq2luocySg==,iv:3tCBux9fwSFO5yRrmN8vGNPvPgrJ21D74dCVwk7N9w4=,tag:3+ThOcUdjSY8392mFxGdTw==,type:str]
    username: ENC[AES256_GCM,data:IogEYT7CB/8=,iv:uKXKv1ddsiuOgAEbe1DJ1k0b8gTUVyaXe568dtlzV/8=,tag:MNonloK9ryAP9vxWaKftKQ==,type:str]
kind: Secret
metadata:
    name: pynuts-influxdb
    namespace: pynuts
    labels:
        app.kubernetes.io/instance: pynuts-heat
        app.kubernetes.io/name: pynuts
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-28T09:32:34Z'
    mac: ENC[AES256_GCM,data:clI1hdThCDwF7s4q6oJu79yvnOkWRoOOFenvYRU7/MtTXvA2FTDD8ieL6PQUzubq2P7FUM9aUR+W0BnO6DbXlgyzxS9nO18IQ6j5WbDb3zM59zLiMM0kdruCJrqhaohsCH+9++S/GJAaSVquo4ERHeRwIom/xzi7qU4h9YLObzk=,iv:kT4qUgVxYPeoEgmLh99SEhA/c+JSvuoTS0O+YRfXTjw=,tag:y/JyQoi4+VT9nKlko5pCAQ==,type:str]
    pgp:
    -   created_at: '2021-06-28T09:32:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ//ZP0V1VnqP82T59L4CcMR6q/qypXJ+8Yf3NWhf2IfH/OJ
            lbxlRGbO87rn0Ky+eDOyojcNCIBJACagOvQ1yWwnkFX59212oXHwJYQ92UMTqWmI
            2u8mSshMfFmhGgoxsAaCp56uzZg7cKZxW4LZLH9k41FcxxKnbliRQYWkgm2vX2nv
            f/EZAxHfKcsPWr6hPvcfzx+9pB+/adyuwdC1I8ZyPAgBt64s13Bi6Qog6yHrrQVY
            UoGSdZTN+T1bOvBzSeBRE7gOmzFyFcZKaOJ1ZYztlsp5pJfjI7JpKLUatyk580PI
            rm5ua48Ks+S1H1bT0FR4LAEC4W246W8k5XzGx+3i4SMrImsrd71zmfvxyZ5FHKMc
            SDHkhHDjP+NE2SZtXAUL5iIqD8jG3YUMAzQg2GWxe7mY8aNgx1ncaRqbt7oKK/cE
            r102srgnp/JMGceWxKEiWh+XvBN2npUNkKQ0eUGbEz3KVDBcXMIsJ5snWbHPOlZC
            UiwBgsdTOlVPDuYj1sjqSpQdMjEhFFeLP1PpgT0sV3YLOlnYYaYcaJUd31LDJPnr
            1Wv4UN2YyWZMv7oaiZyfmJ3uZxi5HbUqQAaOuB+BVap7Ru4d57nIuoluvsVYFHuB
            +bwHZpOU/5EqmkOnjBmx8I9C6Tlgy1UxXL6YxSILPzUPoRHVCD+brob+LdaWgSnS
            XgEexk5JnDZJ6ld9RKKDTm/UwnW2Gj2lSt1nmQHGcyhfGHrjdfRLS9sfcww6jmoi
            Lcew6nvqiLvRaFfHSN3GyNOrkPOx8R38gZSe3jZDueIwwBI5C4pFGYg48WGqLCI=
            =R58r
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
