apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./install/kubernetes/cilium
      version: 1.10.90
      sourceRef:
        kind: GitRepository
        name: cilium
        namespace: flux-system
  values:
    bpf:
      ctTcpMax: 262144
      ctAnyMax: 131072
      lbMapMax: 32768
      policyMapMax: 8192
      natMax: 262144
      neighMax: 262144
      mapDynamicSizeRatio: 0.001
    hubble:
      relay:
        enabled: true
        image:
          tag: v1.10.1
    image:
      tag: v1.10.1
    kubeProxyReplacement: strict
    k8sServiceHost: 9ka.nl
    k8sServicePort: 6443
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    operator:
      image:
        tag: v1.10.1
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    startupProbe:
      failureThreshold: 150
