---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitwarden-rs
  namespace: flux-system
spec:
  url: https://skeen.github.io/helm-bitwarden_rs
  interval: 1h
---
#apiVersion: source.toolkit.fluxcd.io/v1beta1
#kind: HelmRepository
#metadata:
#  name: codecentric
#  namespace: flux-system
#spec:
#  url: https://codecentric.github.io/helm-charts
#  interval: 1h
#---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: codecentric-charts
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: bump-postgres-in-keycloak
  url: https://github.com/jonkerj/codecentric-charts.git
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: influxdata
  namespace: flux-system
spec:
  url: https://helm.influxdata.com/
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  url: https://charts.jetstack.io
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jonkerj
  namespace: flux-system
spec:
  url: https://jonkerj.github.io/charts/
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  url: https://nextcloud.github.io/helm/
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  url: https://oauth2-proxy.github.io/manifests
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: vmware-tanzu
  namespace: flux-system
spec:
  url: https://vmware-tanzu.github.io/helm-charts
  interval: 1h
