apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cert-manager
  namespace: monitoring
spec:
  groups:
  - name: cert-manager
    rules:
    - alert: CertManagerCertExpirySoon
      annotations:
        summary: Cert {{ $labels.name }} is {{ $value | humanizeDuration }} from expiry
        message: Cert {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is {{ $value | humanizeDuration }} from expiry
      expr: (certmanager_certificate_expiration_timestamp_seconds - time()) < (21*24*3600)
      for: 1m
      labels:
        severity: warning
    - alert: CertManagerHittingRateLimits
      annotations:
        summary: Cert manager hitting LetsEncrypt rate limits.
        message: Depending on the rate limit, cert-manager may be unable to generate certificates for up to a week.
      expr: increase(certmanager_http_acme_client_request_count{status="429"}[10m]) > 0
      for: 1m
      labels:
        severity: critical
