apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret
    extraArgs:
      email-domain: "kippendief.biz"
      oidc-issuer-url: "https://sso.9ka.nl/auth/realms/9ka"
      provider: "oidc"
      set-authorization-header: "true"
      show-debug-on-error: "true"
      skip-provider-button: "true"
      whitelist-domain: ".t.efgh.nl"
    image:
      repository: jonkerj/oauth2-proxy
      tag: master
    ingress:
      enabled: true
      path: /oauth2
      hosts:
      - prometheus.t.efgh.nl
      - alertmanager.t.efgh.nl
      - dashboard.t.efgh.nl
      - hubble.t.efgh.nl
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
