apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: talos-controller-manager
	namespace: talos-system
spec:
  template:
    spec:
      containers:
      - name: talos-controller-manager
        env:
        - name: TALOS_TOKEN
          valueFrom:
            secretKeyRef:
              name: talos-token
              key: token
