apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden-rs
  namespace: bitwarden
spec:
  interval: 5m
  chart:
    spec:
      chart: bitwarden
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: bitwarden-rs
        namespace: flux-system
  values:
    bitwarden:
      domain: https://brs.t.efgh.nl
      invitations_allowed: true
      server_admin_email: jorik@efgh.nl
      signups_allowed: false
      smtp_from: jorik@efgh.nl
      smtp_host: 172.21.46.1
      smtp_port: 25
      smtp_ssl: false
    deployment:
      image:
        tag: 1.19.0
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - brs.t.efgh.nl
      paths:
      - /
      tls:
      - secretName: bitwarden-tls
        hosts:
        - brs.t.efgh.nl
    resources:
      requests:
        cpu: 50m
        memory: 25Mi
      limits:
        cpu: 250m
        memory: 100Mi
