apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:g+6VNgMs8mV7+RsrwNQ21tGgR6o7vOmXfmCwytBJIrErh3RKUZZyNY/J+/qkQa14KNFyYOkxnhYl7OHhpjvoJORDZc2ryQsh1eUyj1UfoEeXCM317DPE+oGKRj1CqsnPFNeh1xUVdeowzXEirO2Zs5y7nqU2y5pVD+JBwuGm4oR3f4zANJFVDiZAAn7SP7R60wqs7ZtTYjvqwLKv7ie8ql941iQNR0IwwcmBddeitcQvxDT53mEk15OfKLNow+NVoFjCs7v7Je4WlVwQzbIIY5QFomvhV3FSV1z1rTcG+axZKvmk7fCvFwtIDfhwVVMaky/U1WimSx+M9ZacyLqg04IBeVWRHdq5tTp8eCXsRrTJUi3u+U7u3Bqa6+MjawjPXFjQ9PLo9DKAPqJTWtLGFL3ZZEvdaOT83nkWT9LU7isXrq3zZ8kBm3pnwPibV1hBis21MkhQSpXy9FHXuwpKHu3xf7Ktg1KV2DYca3xS6910CtKKdpWl6UbcDMlMCOwuInX98KZ8yYCSmCrF9ZnB90VH89rwTNqa5HSCUwWQuJaMyhOuBDbKmUvoLPOJ/WMVULr9+UPzUmBwCnFRw/i+jL1VNzbuh2oL3SXKD2E3PuQ7fK/lpuvucZLehvAYOcqeHBnjtUXqsJp1lyYzOhO5ntHXilxVsGhcVOjXI3pkOvXv09p15RJoyaqt9cMXSnnAXoqgxoDjOz9r9Mpgz5k2SpHpcRNGcIIO37kd/hj2czVGSFhKWH5hGjSua2bOBPEreIBPQnzMUfXFWBg8Um2nSw==,iv:lqz7SOtMCSg1J6g0TeCVMdUFekL4q86WWo1EkhAW89M=,tag:Yvt1Cypw7vf3TZXICi4reA==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-07T11:30:38Z'
    mac: ENC[AES256_GCM,data:0Ae9ZCJh23xYkVBU7xjAOlYCO72uTenuyLv+FtYHO49sN4Tyt/URgnQj1AjjqE5xkJj8VyqAY9ZAgar/iSkak0FFaIidwIfKnYiS9hK4suAT/RDfddS7M9879jzpqIVF7mxorTk2VroU17CW1D7EBomsplrVBn429zo5rW9z+c8=,iv:mKcTziTpt8ibH9FmDLJqcEEO9DcJ0HYejTdzdwE5QYs=,tag:Q4lQHNZCG5x5badY3TM+fw==,type:str]
    pgp:
    -   created_at: '2021-02-22T18:54:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAhSHjZVj/Lrn98rOz0Eg7doH0z/ixzCATo7rctWeqYx+H
            8WgmvBA2MegPPpQitY4gamqfvt7AhNBGaNIgZ3DQVqrHXNTtqN/YmlmXvH1+C6d0
            vALFmr87co6hqjAEwQVsz5Ro/DMWVmIFxdgFSrB8WpEc8q2cSSNs50PEr94ZIYGq
            Fr1uXGxAQ6VnTUULSGh77SD1cYtj3+K34konBLsT7PVwEGoAEbEHegKgcH1BVARE
            EsHkJ8KM8JFB0FIj1AFokHH/8nO4Np1/gIiU0RyAJCRwEAOgGsP9lIlCdKukFgT4
            fJwUDEeCpcYWu1FpT2iplLZ/d+wixYY1eED+rBmVIiD5mAD7C876q4SteUJhlC0F
            w1c6LENw6Mho0quVymaIhYjx+s8MD3M7ReZpe0Lvxa1HeibhMCQobXTm55H+2B21
            QKrfYIknifZeR/ALVehBPVf1xdwgcWLzf9oY3sXXrUbqas2rAGGB4KbpENAnbOxb
            II5sQ0Bqh1VgM2StP4lXmOJS9JPSHC4ZfEh812wAltMDw5zjl9Zlo0hrNL67QCiG
            G/oL283PQT3NX3Nysvv5mvufBaYCLmCLxibPwXNH1kElTd6KjBVaFRf9y1kirBme
            GclVtnzkcZMIjDB1RfzigITLhubXKSscFqBYzYqNrO1+iXQkpQTXkHNvcEflHf/S
            XAEXlSx0iMzYw6bcmJyC2Fy0fAbpkOSB0g1wa8DVClj3lMqnAykNOe6b32r7kHbM
            TNlQOTz8RNMqBjrYMVLzNCDyvk1fki11OaIEiTG40cdrXxBewSObflxf97gd
            =l4qZ
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
