apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: strict
    k8sServiceHost: 9ka.nl
    k8sServicePort: 6443
