apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-components.yaml
- flux-sync.yaml
- efgh-sync.yaml
- efgh-helmrepositories.yaml
patchesStrategicMerge:
- flux-resources.yaml
