apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy-prometheus
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    config:
      existingSecret: oauth2-secret
      configFile: |-
        provider = "keycloak"
        login_url = "https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/auth"
        redeem_url = "https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/token"
        validate_url = "https://sso.9ka.nl/auth/realms/9ka/protocol/openid-connect/userinfo"
        upstreams = [
          "http://prometheus-operated:9090/"
        ]
        scope = "email"
        email_domains = [
          "kippendief.biz"
        ]
        skip_provider_button = true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts: ['prometheus.t.efgh.nl']
      tls:
      - hosts: ['prometheus.t.efgh.nl']
        secretName: prometheus-tls
