apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:nNAomw1c8DK3RQmSl0n415HsScYdwVRvjeyec5SyITk6VwhV/MYQXxWCw1XMcH3opl4CYxIAUHikUIR93iPhk8HKpHp+ASg4GCjLtSRlPpO2BOThxsEcb+IErOJGaEYtAtCPgR0+QWF5hVHJgLwc3IM80HdBT2owAe0hV9Tq/3zlFrFU600kd7pmYNDnQg2ArafEG8rSgLFLx7Ne7Lqdv4Kqm227cxJcbYZo3+9Op2eQyQNKI308m9UDKdnx5I+vitkbqhQjdZPoBZLddSQMoRKWXuD73q/91TVpuk2c2kEAfz6V0VEngNuR8EZvX6vPoaYl3s9Uz/1Xyi2e6sRrwF+3T8yNORHIe7iAlIKmkWXCDaglQCEyxwj5jlBiT1fq7zKpaXo0zePAhzBgHFqm3y6CcgGMO3cKNI14Nx/f3Zz/4SgCkWhYlngYSUGBScOsR+TWrPSPqoFkR1T/QTtFNJkhKMU4bzQtovNQrwLi+FQpBV4ozgq+rAxanOeJpFwWKybe9KrOq8icT49se6Y6m0TwdIiC91uM04pDPq9doM9Qgd/fn11Sdwdi1wgBlt3AP+LaKNxv3XqbeK8bD1tOhNeb0e4M5n+ZMZGtL57MAmcrvHsEZOyGU/sc6uc9gQJUEaFDqw70f/S5juUwGtD/zjgiLTeElNo4N9MLfzOH5ZcNb2/uw0SPp6T03WEaNLkh39W5IDDxaLhbTzgJz4HtDsX+MLJhRnZjwzvSu0LCpMOEaW3j/0DTad8sIuuz2GzjE98vUJflkxSx1WDTwLn6KyTCZS26RskZHaqamfkcIhAs3V3XWPPft8me06pukwh72pIQjSznZiqhdmKLJlQeBy0tfbi8DpxMMldflaxiHCWUq4hqiccsm+YYVdo6vutsBWeuSIvUE5EUTvj+dw3WzJhIfnl8LMQtSpmh2cZuwj5K57pkm4rL9DrGsDVTHPE/hJMd02V1+maQ0SFCSKtKudrQ2bf5r2zkeLlz0F/d+ISjtQpf,iv:r1bhGPmIGJHgAxNzbkSuDFRbdCJZHVhQJbOT4UfsKbs=,tag:bEf+ditUSfFv8weCtn7LwA==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-22T18:54:50Z'
    mac: ENC[AES256_GCM,data:Hl2/QtLiz5qcM72wLZf+wCANHat0a7OKeG0itnoHk3bm6hCqyrDrib9//EZIQ4V+ByuyepfGW/9OmkBNAIhI7mhQDIOPbAIKoZRV3u8AYn416eQuFdOH3wq3c0YUYTSPg10sQGMFXM5iCxdLml6F5H4CmyNa4ng/vPn3aEZe77Q=,iv:t/hb8Ed0q181LLtcQLByjrTIFrx3jZPJxhVjsid1sPQ=,tag:C5QBEodUzCInaT82o02jvg==,type:str]
    pgp:
    -   created_at: '2021-02-22T18:54:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAhSHjZVj/Lrn98rOz0Eg7doH0z/ixzCATo7rctWeqYx+H
            8WgmvBA2MegPPpQitY4gamqfvt7AhNBGaNIgZ3DQVqrHXNTtqN/YmlmXvH1+C6d0
            vALFmr87co6hqjAEwQVsz5Ro/DMWVmIFxdgFSrB8WpEc8q2cSSNs50PEr94ZIYGq
            Fr1uXGxAQ6VnTUULSGh77SD1cYtj3+K34konBLsT7PVwEGoAEbEHegKgcH1BVARE
            EsHkJ8KM8JFB0FIj1AFokHH/8nO4Np1/gIiU0RyAJCRwEAOgGsP9lIlCdKukFgT4
            fJwUDEeCpcYWu1FpT2iplLZ/d+wixYY1eED+rBmVIiD5mAD7C876q4SteUJhlC0F
            w1c6LENw6Mho0quVymaIhYjx+s8MD3M7ReZpe0Lvxa1HeibhMCQobXTm55H+2B21
            QKrfYIknifZeR/ALVehBPVf1xdwgcWLzf9oY3sXXrUbqas2rAGGB4KbpENAnbOxb
            II5sQ0Bqh1VgM2StP4lXmOJS9JPSHC4ZfEh812wAltMDw5zjl9Zlo0hrNL67QCiG
            G/oL283PQT3NX3Nysvv5mvufBaYCLmCLxibPwXNH1kElTd6KjBVaFRf9y1kirBme
            GclVtnzkcZMIjDB1RfzigITLhubXKSscFqBYzYqNrO1+iXQkpQTXkHNvcEflHf/S
            XAEXlSx0iMzYw6bcmJyC2Fy0fAbpkOSB0g1wa8DVClj3lMqnAykNOe6b32r7kHbM
            TNlQOTz8RNMqBjrYMVLzNCDyvk1fki11OaIEiTG40cdrXxBewSObflxf97gd
            =l4qZ
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
