apiVersion: v1
data:
    alertmanager.yaml: ENC[AES256_GCM,data:xggP9kRiascbF+PD/Y+bwmJk5H82MNGO0Ad30bBrS2kJjFd7S3/2UC7aQnt8PfvJs0ct5+D9ASux8YLjanctGsNcRTFyScUDZYgaswjtnWqLFPJ0jNn42Jk0yNL7LWpR6zMvCGs6/upIbAntYxLNipVPBuXfUEJb4GWzE8OyNZHa47kKfkUtL1MhlkC0Wg+lfbMfUEAf+L8W2+QCp9rcR7iI7c0AcbIBmw/zKC5aMvKm+3rAi00WvrpzlnQaUntA5xo59PSzuCCeJ0naiuEbMG8/6f2+jnimuQAtuYrpQNphyijl8aolLvNLeKLvH6UYCNwnYrLf0kDj/MWj9kqkifFzSYElCAI4T/JFsrwWC2FHUQYME6Ngr2VODdWwg6ubxuWUHj/xtIC7gRRfVt+/0+rK3WrOevJYmaDE3qbNUWIa1QATbxYFqK6mTWGrxZSDmAA1m0vHMjU1USCw93aFUEdeE1jtzgabOyqGA0x+sYog1yH4MvBDwxQtxVweALZzxA4eQFm1TTTAu1NJNRM3jRXl5LV77CUpVUKMib+KFpIJsQUdMuifh2UHn1axk0X2RTKUgYx8UQR9H4bDDFutsdF61piFKzhrjRQSepZHUtXyCqDS3VWlmzLeXfixQjTJgxqyL/aephIBd8DNWfvW1j7vXH4ge/4gi8tf4Lg2YfxUDRcP7oDm4zC5deYH0FjMU6QlQYmFxZ39GvoFXhEcVgHMcxgRudGSYsBjfzxA136WOrQpDGeVFhii36L25RWLPMg7jjYzaRmXAplgoyQjgr17XjNtAHL6RtBVZPEyces6J2Ffun/N+E5+q96Umpcbaunh/shqWpCiuaM7AvpZRw1Vq549QK5hcH7Aw7zMMO3PLc40Ro3+iY+hwtwNwvOIyCLIp70ybb487jD2XslwLLr+IeVoSK3cixlFnQMnn+sprjIkgJUmNwtJDBgZ7uFVgNZknKyzntHW8g9y,iv:kjfymppS0yMFYulubjy51C0yX2Ufax59ATkMcgrNd00=,tag:ywqZxUqUNTmlWLrHjL/Png==,type:str]
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-30T13:31:03Z'
    mac: ENC[AES256_GCM,data:vA7SfPtlojkjeEgSX9GvqMcSZsHF2rfnGBBNAHpnngHVo+S1L9Yf3XAw9kxDKoUITQkp09hyv4PnroakQ5VFdTHjh4XlNWH8A1BrjwgRyJ/tNsQzmSsDqCMXivVDjruJLAKD2QaejKFzqythUz8Ra/Ak8pNnfTmO3eRxLqEZcoE=,iv:s/R7EWlOzt7igQ3o+/jVglI2tE1JDBALgbhVOnlC7os=,tag:G9uK4oV4Hicdgr++edTQPw==,type:str]
    pgp:
    -   created_at: '2021-02-22T18:54:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6ARAAhSHjZVj/Lrn98rOz0Eg7doH0z/ixzCATo7rctWeqYx+H
            8WgmvBA2MegPPpQitY4gamqfvt7AhNBGaNIgZ3DQVqrHXNTtqN/YmlmXvH1+C6d0
            vALFmr87co6hqjAEwQVsz5Ro/DMWVmIFxdgFSrB8WpEc8q2cSSNs50PEr94ZIYGq
            Fr1uXGxAQ6VnTUULSGh77SD1cYtj3+K34konBLsT7PVwEGoAEbEHegKgcH1BVARE
            EsHkJ8KM8JFB0FIj1AFokHH/8nO4Np1/gIiU0RyAJCRwEAOgGsP9lIlCdKukFgT4
            fJwUDEeCpcYWu1FpT2iplLZ/d+wixYY1eED+rBmVIiD5mAD7C876q4SteUJhlC0F
            w1c6LENw6Mho0quVymaIhYjx+s8MD3M7ReZpe0Lvxa1HeibhMCQobXTm55H+2B21
            QKrfYIknifZeR/ALVehBPVf1xdwgcWLzf9oY3sXXrUbqas2rAGGB4KbpENAnbOxb
            II5sQ0Bqh1VgM2StP4lXmOJS9JPSHC4ZfEh812wAltMDw5zjl9Zlo0hrNL67QCiG
            G/oL283PQT3NX3Nysvv5mvufBaYCLmCLxibPwXNH1kElTd6KjBVaFRf9y1kirBme
            GclVtnzkcZMIjDB1RfzigITLhubXKSscFqBYzYqNrO1+iXQkpQTXkHNvcEflHf/S
            XAEXlSx0iMzYw6bcmJyC2Fy0fAbpkOSB0g1wa8DVClj3lMqnAykNOe6b32r7kHbM
            TNlQOTz8RNMqBjrYMVLzNCDyvk1fki11OaIEiTG40cdrXxBewSObflxf97gd
            =l4qZ
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
