apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: talos-system-content
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/talos/talos-system/content/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
  - name: talos-system-crd
