apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: talos-system-app
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/talos/talos-system/app/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  dependsOn:
  - name: talos-system-crd
  healthChecks:
  - kind: DaemonSet
    name: talos-controller-manager
    namespace: talos-system
    apiVersion: apps/v1
