apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-admin
  labels:
    app.kubernetes.io/name: pdns-admin
    app.kubernetes.io/instance: pdns-admin-efgh
    app.kubernetes.io/version: 0.2.3
  namespace: pdns-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pdns-admin
      app.kubernetes.io/instance: pdns-admin-efgh
      app.kubernetes.io/version: 0.2.3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pdns-admin
        app.kubernetes.io/instance: pdns-admin-efgh
        app.kubernetes.io/version: 0.2.3
    spec:
      containers:
      - name: pdns-admin
        image: ngoduykhanh/powerdns-admin:0.2.3
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: pda-data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 12
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
      volumes:
      - name: pda-data
        persistentVolumeClaim:
          claimName: pda-data
