apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:eNfrK+IOAdokmXrJ,iv:O5lgUIeifWbfK2HcuUrshpvR+Ek4baOS/ZYBvlpvQYY=,tag:t01yObEBhdSCcQFKNwtHGA==,type:str]
    client_secret: ENC[AES256_GCM,data:BY7V8eRS1lSB6AOo1EgC9FMcczM1DUaebg4pVPkQ4uUC2QUFx/KMRegTcPg=,iv:W4FcyPNEu5E7I5ee1YwzHCGARHmK1bC+nAUc/fwf2Cw=,tag:gUDs9DSEuUdq0QI/eTAFQw==,type:str]
kind: Secret
metadata:
    name: grafana-generic-oauth
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-07-13T09:23:53Z'
    mac: ENC[AES256_GCM,data:z6E3xbQNtUVWuEs3Q5lLF+j7a7jrDN6hxvu97Bv4uad95ZQZAYSpbCH4USVmOIHMpW+G3EWYZft64HFsjmVmn6GDZ16L0yMVKQmIYTfG4AFu09myIcN36oy0u2MkblOR9yz8tPvqFQi/XXyh+TWxnrqW/cBedxoxLqm3uwow6sQ=,iv:FrUS+M+vfZVxSqFWnPfUriViFj0SfTuSkrZnJoKYOPg=,tag:jDfNxUzinAFglGthf3JLpQ==,type:str]
    pgp:
    -   created_at: '2021-02-22T13:52:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA59YQxrIsWI6AQ/7BhOjW/qVTl8fHkcPWoqDahAUCiN9aAgxsS4mYutb/n3A
            696VNUOAW72T4gLaGM5NRb6Egd7jvApXJNGyxWlIJO6pmlWl0p4QFn6K48kyxV24
            HrZnSfSLAIaDjF0pdVKk1kRa7nXwcqRz9lYF8pIRvRW/Ew7RDKUHBj2dsQaX5uTW
            D5q76KwZMZBfwapNx9CBAEcsUv9jHx5byLZWQKQmNfgWadNfCdn/krXSJA1sNdBN
            tTpBATfOZB0+q+0j/UWNeFJS58nA3eq51nQTG4iGQfAjq/V48hBeE5xfLBC3CUmR
            GaK4hilZyaeHMCylod0qylK96kN9GbLtiR81cJ4aY8/888/tj3NGHbWDGfxTyyhz
            stF3Ij1LDYedjpRjyvl8jP6MDby89/A+/9M08dOVh4VhgpobXGu6lIOsndMOl4qy
            dNmJM3qs2tBBrLlBqF817rJar+GhsookZyhA+hhKDgmvkKF7swUsUXkgq9icKQ+A
            9OPXTgxm2UXdYDmGp+9g9Y/Jc2qrG5wCZUdROyqsOGoOpjZyDm6JSkEgIx0OkSzu
            zOuDj3OYxH6u+VUeKhN4uyKsZ+g5fsvIOnoPyxi+iXwZ6HRYOj2SPGzmlqJGm/Pd
            lWaTNErVHvAVQFGI8+OdyRJAUQ6ZbQFgSqpcQcNcBnP82ndLPJcEXni5qIcskubS
            XAFGqnz1R2wDeQbOT4CpeU1EUFtbzK9Wf5ugsQjRrfAdqKBdSm6u0sdnRXxMfhKz
            L2Xwk+2PV2QG4J1xu3rdkMOBNm9pnxYcIpMmmXGhCSeMZlYesJAwN/zu5mvf
            =DYmT
            -----END PGP MESSAGE-----
        fp: 4D72B62BB844B05E12DEC3A9A3AEC49250A67E2A
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
