apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  values:
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      rules:
      - host: sso.t.efgh.nl
        paths:
        - /
      tls:
      - secretName: keycloak-tls
        hosts:
        - sso.t.efgh.nl
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    pgchecker:
      resources:
        limits:
          cpu: "10m"
          memory: "32Mi"
    postgresql:
      enabled: true
      livenessProbe:
        failureThreshold: 24
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
