apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-crd
  namespace: flux-system
spec:
  interval: 10m
  path: "./cert-manager/crd/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube-cd
    namespace: flux-system
  healthChecks:
  - kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
    apiVersion: apiextensions.k8s.io/v1
