apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
  - name: cert-manager-crd
  interval: 10m
  path: "./cert-manager/issuer/"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: kube-cd
    namespace: flux-system
  healthChecks:
  - kind: ClusterIssuer
    name: letsencrypt
    apiVersion: cert-manager.io/v1
